### ISSUE TITLE
ResponseBody not writing out

### ISSUE THREAD

**Issue by mcasper** [iron/iron#410]
@mikeastock and I are trying to use `ResponseBody` to read the body of an `iron::response::Response` in order to test our Handlers (in conjunction with reem/iron-test). However, it seems that `ResponseBody` is not able to write its buffer back out to something that can be read (like an `&[u8]`), making it impossible make assertions about the response body. The following code models the problem:

```Rust
fn hello_world_handler(_: &mut Request) -> IronResult<Response> {
    Ok(Response::with((iron::status::Ok, "Hello, world!")))
}

fn main() {
    let data = Cursor::new(Vec::new());
    let mut stream = MockStream::new(data);
    let mut reader = BufReader::new(&mut stream as &mut NetworkStream);
    let mut req = request::new(method::Get,
                               Url::parse("http://localhost:3000/users").unwrap(),
                               &mut reader);

    let response = hello_world_handler(&mut req).unwrap();
    let f = ::std::fs::File::create("/tmp/test").unwrap();
    let mut response_body = ResponseBody::new(f);
    response.body.unwrap().write_body(&mut response_body).ok();

    let mut result = Vec::new();
    response_body.write(&mut result).ok();

    assert_eq!(result, b"Hello, world!");
}
```
Running the code shows that nothing was ever written to `result`:
```
thread '<main>' panicked at 'assertion failed: `(left == right)` (left: `[]`, right: `[72, 101, 108, 108, 111, 44, 32, 119, 111, 114, 108, 100, 33]`)', src/main.rs:33
```
And if we were to inspect the `usize` returned by the `response_body.write()` call, we would see that it is indeed 0.

However, if you look at the file we used as the initial buffer:
```
cat /tmp/test
Hello, world!%
```
You'll see that we did extract the body successfully from the `Response`.

So the problem seems to be with `ResponseBody`, was wondering if we could get any guidance on this.

Thanks guys!

**Comment by reem** [comment]
Hmm, I think I know what's going on. Try replacing the final lines with:

```rust
let mut result = vec![0; b"Hello World!".len()];
response_body.write(&mut *result).ok();

assert_eq!(result, b"Hello, world!");
```

I think the impl of io::Write for Vec might not be doing what we want.

**Comment by mcasper** [comment]
We got bytes!

```
thread '<main>' panicked at 'assertion failed: `(left == right)` (left: `[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]`, right: `[72, 101, 108, 108, 111, 44, 32, 119, 111, 114, 108, 100, 33]`)', src/main.rs:33
```

**Comment by reem** [comment]
Oh man, sorry, total red herring. The real problem is just that `ResponseBody` is an `io::Write`, and calling `write` on it is for *adding* data to it, not reading it out.

The appropriate thing to do is something like this:

```rust
fn hello_world_handler(_: &mut Request) -> IronResult<Response> {
    Ok(Response::with((iron::status::Ok, "Hello, world!")))
}

fn main() {
    let data = Cursor::new(Vec::new());
    let mut stream = MockStream::new(data);
    let mut reader = BufReader::new(&mut stream as &mut NetworkStream);
    let mut req = request::new(method::Get,
                               Url::parse("http://localhost:3000/users").unwrap(),
                               &mut reader);

    let response = hello_world_handler(&mut req).unwrap();

    // Create an io::Write we can write into.
    let mut result = Vec::new();
    {
        // Give ResponseBody the Vec as a target to write to.
        let mut response_body = ResponseBody::new(result);
        // Write from the response body -> ResponseBody -> Vec
        response.body.unwrap().write_body(&mut response_body).ok();
    }

    // Read the contents of the Vec
    assert_eq!(result, b"Hello, world!");
}
```

**Comment by mcasper** [comment]
Oh wow, yeah that did the trick! 

Sorry about that, and thank you very much :smile:

**Comment by reem** [comment]
No problem :)
